# Generated by Django 5.2.5 on 2025-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_experience_years_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=20, null=True),
        ),
    ]
