# Generated by Django 5.2.6 on 2025-10-10 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('experience', models.PositiveSmallIntegerField()),
                ('mode', models.CharField(choices=[('text', 'Text'), ('voice', 'Voice')], max_length=10)),
                ('webcam_enabled', models.BooleanField(default=False)),
                ('questions', models.JSONField()),
                ('answers', models.JSONField()),
                ('voice_transcripts', models.JSONField(blank=True, null=True)),
                ('interaction_feedback', models.TextField(blank=True, null=True)),
                ('ai_feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
