# Generated by Django 5.2.7 on 2025-12-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_add_score_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewresult',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='interview_audio/'),
        ),
        migrations.AddField(
            model_name='interviewresult',
            name='video_frames_zip',
            field=models.FileField(blank=True, null=True, upload_to='interview_videos/'),
        ),
    ]
