# Generated by Django 5.2.7 on 2025-12-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_interviewresult_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveSmallIntegerField()),
                ('question_text', models.TextField()),
                ('audio_file', models.FileField(upload_to='question_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_audios', to='feedback.interviewresult')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('interview', 'question_number')},
            },
        ),
    ]
