# Generated by Django 5.2.7 on 2025-12-07 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_questionaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresult',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='interviewresult',
            name='video_frames_zip',
        ),
        migrations.DeleteModel(
            name='QuestionAudio',
        ),
    ]
